### ISSUE TITLE
The architecture fig is not clear

### ISSUE THREAD

**Issue by pinyuko** [MicrosoftDocs/cloud-adoption-framework#600]
[Enter feedback here]

https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/sap/media/overview-architecture.png
The architecture fig is not clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa4f1fff-2485-a841-1b26-aa9601d2a121
* Version Independent ID: d8f114ec-93c2-f30b-6ac8-bfa47160813b
* Content: [Enterprise-scale for SAP on Azure - Cloud Adoption Framework](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/sap/enterprise-scale-landing-zone)
* Content Source: [docs/scenarios/sap/enterprise-scale-landing-zone.md](https://github.com/MicrosoftDocs/cloud-adoption-framework/blob/master/docs/scenarios/sap/enterprise-scale-landing-zone.md)
* Service: **cloud-adoption-framework**
* Sub-service: **scenario**
* GitHub Login: @JefferyMitchell
* Microsoft Alias: **brblanch**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/490415/>490415</a>

**Comment by v-andreaco** [comment]
Fixed in private repo PR https://github.com/MicrosoftDocs/cloud-adoption-framework-pr/pull/2584

**Comment by pinyuko** [comment]
Hi @v-andreaco 
It's been 6 months as I submitted this feedback, and I noticed the current fig on https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/sap/enterprise-scale-landing-zone is still not clear.
Would you kindly share when that will be fixed? Thank you!

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/1679118/156664437-894e1c64-54b0-4b0a-879e-3973a738abec.png">

**Comment by v-andreaco** [comment]
@pinyuko 

Thanks for bringing this to our attention! It looks like lightbox was successfully added, but you're right - that image still isn't clear. I've reached out to see if we can track down the original vector file and get a higher resolution version. I'm reopening this issue and will update you when I hear back.

**Comment by hallihan** [comment]
@pinyuko We're taking another look at this, can you provide details on what was not clear? Is it just readability or is there something conceptual that we can address.

**Comment by pinyuko** [comment]
The picture resolution now is good. Previously it's blurry. Thanks for following up. You may close this thread now.
